{% set name = "ansible-core" %}
{% set version = "2.14.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 47f0d4b4125b58edba6435a47f37cbe6a18da54594d18f812958bb0cb58d4e65

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - cryptography
    - jinja2 >=3.0
    - packaging
    - python >=3.8
    - pyyaml
    - resolvelib <0.6.0,>=0.5.3

test:
  imports:
    - ansible
    - ansible._vendor
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://ansible.com/
  summary: Radically simple IT automation
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - mariusvniekerk
    - etcet
