{% set name = "ansible-core" %}
{% set version = "2.16.2" %}
{% set version_major_minor = ".".join(version.split(".")[:2]) %}

{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e4ab559e7e525b1c6f99084fca873bb014775d5ecbe845b7c07b8e9d6c9c048b

build:
  number: 0
  entry_points:
    - ansible=ansible.cli.adhoc:main
    - ansible-config=ansible.cli.config:main
    - ansible-console=ansible.cli.console:main
    - ansible-doc=ansible.cli.doc:main
    - ansible-galaxy=ansible.cli.galaxy:main
    - ansible-inventory=ansible.cli.inventory:main
    - ansible-playbook=ansible.cli.playbook:main
    - ansible-pull=ansible.cli.pull:main
    - ansible-vault=ansible.cli.vault:main
    - ansible-connection=ansible.cli.scripts.ansible_connection_cli_stub:main
  noarch: python

requirements:
  host:
    - setuptools >=45.2.0
    - pip
    - python {{ python_min }}
  run:
    - cryptography
    - jinja2 >=3.0.0
    - packaging
    - python >={{ python_min }}
    - pyyaml >=5.1
    - resolvelib >=0.5.3,<1.1.0
    # https://docs.ansible.com/ansible/latest/user_guide/windows_faq.html#can-ansible-run-on-windows
    - __unix

test:
  imports:
    - ansible
  commands:
    - pip check
    # Ensure ansible ignores system locations for its modules
    - ansible --version | grep -v /usr/share/ansible
    - ansible-config --version
    #- ansible-connection --version  # hangs waiting for input
    - ansible-console --version
    - ansible-doc --version
    - ansible-galaxy --version
    - ansible-inventory --version
    - ansible-playbook --version
    - ansible-pull --version
    - ansible-test --version
    - ansible-vault --version
  requires:
    - pip

about:
  home: https://ansible.com/
  summary: Radically simple IT automation
  license: GPL-3.0-or-later
  license_file: COPYING
  doc_url: https://docs.ansible.com/ansible-core/{{ version_major_minor }}/index.html
  dev_url: https://github.com/ansible/ansible

extra:
  recipe-maintainers:
    - pavelzw
    - mariusvniekerk
    - etcet
    - chenghlee
