{% set name = "ansible-core" %}
{% set version = "2.14.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8c4eed76ce458b4a37334a0802df29488ecf9f8af38c3111069c96b17b205530

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - cryptography
    - jinja2 >=3.0
    - packaging
    - python >=3.8
    - pyyaml
    - resolvelib <0.6.0,>=0.5.3

test:
  imports:
    - ansible
    - ansible._vendor
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://ansible.com/
  summary: Radically simple IT automation
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - mariusvniekerk
    - etcet
